version: "3.9"

services:
  # -----------------------------------------------------------
  # Postgres Database
  # -----------------------------------------------------------
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # -----------------------------------------------------------
  # Keycloak Authentication Server
  # -----------------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always

    # Use the new "start-dev" command for Keycloak 17+ in dev mode
    command: >
      start-dev 
      --hostname-strict=false

    # Required environment variables
    environment:
      # Create admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database configuration (KC_ prefix)
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public

      # (Optional) Additional settings
      KC_HOSTNAME_STRICT: "false" # So you can access Keycloak from any hostname while in dev

    depends_on:
      - postgres

    ports:
      - "58080:8080" # Port for the Keycloak UI / REST
      # - "58443:8443" # If you configure SSL for dev (often omitted in dev mode)

    volumes:
      - keycloak_data:/opt/keycloak/data

  # ✅ Redis (For caching & sessions)
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - "56379:6379"

  # ✅ API Service (Golang + Echo)
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
      target: dev
    restart: always
    depends_on:
      - postgres
      - keycloak
    ports:
      - "53000:3000"
      - "52345:2345"
    volumes:
      - ../api:/app
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: fitnis
      REDIS_URL: redis:6379
      KEYCLOAK_ISSUER_URL: http://keycloak:8080/realms/fitnis
      KEYCLOAK_CLIENT_ID: my-client
      KEYCLOAK_CLIENT_SECRET: my-secret

  # ✅ Frontend Service (React/Vue)
  # frontend:
  #   build: ./frontend
  #   restart: always
  #   depends_on:
  #     - api
  #     - keycloak
  #   ports:
  #     - "55173:5173"

volumes:
  postgres_data:
  keycloak_data:
